name: signals
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - scipy
  - pandas
  - pip
  - ipython
  - jupyter
  - nbconvert
  - matplotlib
  - nb_conda_kernels
  - pip:
      - jupyter-book
      - ghp-import