name: signals
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - scipy
  - pandas
  - pip
  - ipython
  - jupyter
  - nbconvert
  - matplotlib
  - nb_conda_kernels
  - nbsphinx
  - myst-parser
  - myst-nb
  - sphinx
  - sphinx-book-theme
  - sphinx-copybutton
  - sphinx-design
  - sphinx-jupyterbook-latex
  - sphinxcontrib-bibtex
  - pip:
      - jupyter-book
      - ghp-import